on: workflow_dispatch
jobs:
  submodule-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello, world!!"
      - uses: peter-evans/create-pull-request@v4
        with: 
          commit-message: submoduleの更新
          branch: submodule-update
          title: submoduleの更新
          body: