on: 
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  submodule-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: |
          cd char-array-list/
          git checkout main
          git checkout $(git describe --tags --abbrev=0)
      - uses: peter-evans/create-pull-request@v4
        with: 
          commit-message: submoduleの更新
          branch: submodule-update
          title: submoduleの更新
          body: ""